### ISSUE TITLE
Dealing with CGM false reading (drops or spikes) due to bad sensor or calibration

### ISSUE THREAD

**Issue by amazaheri** [openaps/openaps-js#14]
How about adding:

 if ((glucose_status.delta >= 20) || (glucose_status.delta <= -20)){
        console.error('Error: Potential faulty CGM reading, waiting for 5 minutes');
        process.exit(1);
    }

we can increase or decrease the number.

  {
    "trend_arrow": "NOT_COMPUTABLE",
    "system_time": "2015-08-01T12:34:32",
    "display_time": "2015-08-01T04:32:56",
    "glucose": 83
  },
  {
    "trend_arrow": "SINGLE_DOWN",
    "system_time": "2015-08-01T12:29:32",
    "display_time": "2015-08-01T04:27:56",
    "glucose": 64
  },
  {
    "trend_arrow": "FLAT",
    "system_time": "2015-08-01T12:24:32",
    "display_time": "2015-08-01T04:22:56",
    "glucose": 88
  },

If we are in agreement I push the change, open to other suggestions.

**Comment by scottleibrand** [comment]
I would rather just turn off the discrepancy / avg delta stuff when the difference between the current delta and the 10-15m ago delta is >2x or something like that. 
We should always respond with a low-temp to a low reading, we just shouldn't assume that the trend will continue. 

-Scott

```
_____________________________
```

**Comment by amazaheri** [comment]
Thumbs up!
