### ISSUE TITLE
Bolus instead of high temp basal

### ISSUE THREAD

**Issue by infoneo** [openaps/openaps-js#16]
I wonder if it would be better to use bolus instead of high temp.

disadvantages of high temp basal:
- high temp is limited up to 6.4U - issue https://github.com/bewest/decoding-carelink/issues/116
- high temp "speed" is limited to duration of 30min.

After last hypo I have taken to much carbs. I noticed, there was no chance to prevent high bg automatically. Only manual boluses left.

**Comment by amazaheri** [comment]
I usually do the Bolus manually via openaps use pump bolus when is needed, not at the stage to rely on APS sending bolus commands automatically. My 2 cents.

**Comment by scottleibrand** [comment]
Think about the situation where a large high-temp or bolus is warranted,
and OpenAPS (tries to) issue one, but then connectivity to the pump is
interrupted.  It then decides that, since it doesn't know that the command
has already been issued, another one is warranted.  If the command is a
bolus, it doesn't take very long in that state to deliver a
hypoglycemia-inducing (and potentially fatal) amount of insulin.

There are definitely ways to mitigate that, but the decision I made in
creating the OpenAPS reference design is to always stick with just temp
basals.  In addition to the safety benefits in the scenario above (where
issuing the same temp basal over and over has no additional effect), it
also means it's possible to cancel a large ongoing temp basal if you see BG
start to drop, which provides an additional layer of safety.

-Scott

**Comment by infoneo** [comment]
The first protection for doubling boluses is already in the loop.sh (lock for single instance of bash script), the second protection may be added in by double checking status.json (if bolusing != false die). In addition in .js we can use equivalent for maxsafebasal (maxsafebolus) ;)

Tempbasals have another disadvantage - without logging to rpi we don't see temp-basal history (or I don't know where to search in the pump menu :)

Additional protection like canceling basals is only possible when dosing insulin is delayed, but if we look from another side - if we want to simulate human reactions...  what we do, if we see for example bg 200mg and climbing trend of bg... 2,5U delayed for 30 minutes??? (6U minus standard basal about 1U divided by 2) 

We already have delays caused by CGMs readings, insulin absorption etc... do we have to add additional delay?

**Comment by amazaheri** [comment]
ub

**Comment by amazaheri** [comment]
Look at sendtempbasal-azure.js, I added that so I can send temp basal requests to an azure SQL for notification and reporting, You can create ur own end point or use NS API to add them to treatments collection.
While you can implement the logic u r proposing I tend to agree with @scottleibrand on sticking to OpenAPS reference design.
![wp_ss_20150727_0002](https://cloud.githubusercontent.com/assets/8312775/9126208/6f9f416e-3c5f-11e5-8a19-17a379251a11.png)
![wp_ss_20150805_0001](https://cloud.githubusercontent.com/assets/8312775/9126209/6fa3603c-3c5f-11e5-918e-859001fb068c.png)

**Comment by scottleibrand** [comment]
Adding openaps-dev list, as we get this question a lot. Thanks for the good discussion so far. :-)
Those protections (against repeated boluses) are insufficient. If you consider the possibility of two Pi's both running OpenAPS at the same time (like we have, to overcome the Carelink range issues) it is actually not possible to avoid the possibility of duplicating a bolus without a 100% reliable pump history query mechanism, with zero possibility of race conditions. Given how pump communications work, that is not something we can count on. For temp basals, by contrast, it's sufficient to have a reasonably accurate pump history (showing what basals have been delivered recently). In a race condition there, the worst case is just fine: the two Pi's both try to administer slightly different basals, and the most recently administered one takes effect until the next successful pump history refresh. 
There is also no need (in my experience) to react that quickly/strongly except for carbs. When BG is rising for any other reason, it either is prone to quick reversals (stress spikes) or rises gradually and can me handled fine by temp basals. For carbs, we want to rely on the human to bolus properly for the carbs consumed, as providing OpenAPS the power to bolus (or even high-temp) sufficiently to offset carbs also means giving it the power to administer more insulin than can be safely counteracted with just carbs, which is a situation I would never want to be in with this kind of a system. 
We are currently configured with a maximum temp basal of 2.5-3U (depending on current basal schedules: basically max temp is 2x max daily basal). That has proven more than sufficient to keep BG in range with appropriate carb bolusing, and able to safely recover when we don't bolus sufficiently for excess carbs. 
The one change I think I would like to make is to relax the "only high-temp when delta is >= 0" rule, in the condition where BG is > 200, eventualBG > 160, and delta > -5 or so. That way we can continue high-temping to bring BG down faster when BG is riding high and flat. 

-Scott

```
_____________________________
```
