### ISSUE TITLE
Software tests, reliability, and best practices

### ISSUE THREAD

**Issue by oskarpearson** [openaps/openaps-js#22]
Hi

I've been reviewing the code and setup, and I am concerned that the project is not yet "ready for prime time". I understand it's early days - but some of the core things that ensure reliability of software like this are missing. These include
- Tests
- Error and exception handling
- Documentation

We must be extremely wary of encouraging people to use the code when they cannot review and understand the code themselves, and make a meaningful assessment of the risks they are taking in doing so!

In the meantime, I think we must put _serious_ effort into improving the code quality, adding tests, and adhering to best practices.

**Comment by oskarpearson** [comment]
I'm starting this process, and will be submitting pull requests to improve the code as I go. However, I'd strongly encourage EVERYONE in this project to review them carefully, and even consider a "3 confirmations" rule before merging changes.

**Comment by oskarpearson** [comment]
Just to be clear.. I think it's _absolutely great_ that this has been released. Please don't take the above personally.

I just think it's important that we recognise that we're definitely still in the "hack something together and hope it works" phase, rather than "everyone can use it - just run these commands and you'll be fine" phase.

Has anyone got any ideas about how best to tackle this?

**Comment by scottleibrand** [comment]
Agreed. Right now I'm still running in the "hack something together for @danamlewis" mode, and probably need to start doing a lot more tests. Not sure if I should switch to developing on my own branch yet and submitting PRs to master, since @amazaheri and @esteward both have their own forks and pull changes over from master before testing and using them. 

I think first step is to set up a testing framework. If you can help with that, I'll be happy to start adding meaningful tests for everything the code should be doing.

**Comment by amazaheri** [comment]
Agreed, @scottleibrand  maybe it makes sense switch to private now and add tests, documentation, etc. and accept folks on one to one basis like Roundtrip project. And turn the repo back to public after we are done with v1, thoughts?

**Comment by scottleibrand** [comment]
I just today added a basic unit test framework (mocha and should.js) to a new branch of openaps-js (https://github.com/openaps/openaps-js/tree/test-refactor), and as the name implies, refactored determine-basal.js to be appropriately functional and testable.  I then added a bunch of test cases to https://github.com/openaps/openaps-js/blob/test-refactor/tests/determine-basal.test.js to test most of the situations we'll see in the low glucose suspend portion of the code (https://github.com/openaps/openaps-js/blob/test-refactor/bin/determine-basal.js#L154-L169) and  the setTempBasal function (https://github.com/openaps/openaps-js/blob/test-refactor/bin/determine-basal.js#L290-L309).

If you'd like to help out with defining all the desired behaviors in the form of unit test cases, please clone / checkout the test-refactor branch of openaps-js (https://github.com/openaps/openaps-js/tree/test-refactor), do `sudo npm install -g mocha` and `sudo npm install -g should`, and then you should be able to run `make` (or something like `mocha -c tests/determine-basal.test.js 2>&1 | less -r`) from the openaps-js directory to run all of the unit tests, including any new ones you add.

We'll want to cover every section of the code, so if you see a "rT.reason" in bin/determine-basal.js that doesn't have a corresponding "output.reason.should.match" line in an appropriate test in tests/determine-basal.test.js, then you should figure out what glucose, temp basal, iob, and profile inputs would get you into that section of the code (preferably representing what you're likely to see in a real-world situation), and create a test case to capture those inputs and the desired outputs.  Then run the tests and see if your test passes, and the output looks reasonable.  If not, then modify your test case accordingly, or if you think you've found a bug in determine-basal.js, hit someone up on Gitter (https://gitter.im/nightscout/intend-to-bolus) or open an issue (https://github.com/openaps/openaps-js/issues) for help tracking down what the desired behavior is in that situation.

Thanks in advance for the help!

**Comment by oskarpearson** [comment]
@scottleibrand That's a great move. Thanks!

**Comment by bewest** [comment]
Thanks all. :smile_cat: Really glad we're able to start adopting rigorous methods as a community.
