### ISSUE TITLE
Dexcom BG value during errors

### ISSUE THREAD

**Issue by channemann** [openaps/openaps-js#24]
In reference to: https://github.com/openaps/openaps-js/blob/master/bin/determine-basal.js#L141

I once saw my Dexcom send back a value of 11 at the beginning of a "???" span. The ones after that were 10, but might be worth increasing this threshold value.

**Comment by scottleibrand** [comment]
Yeah, we should probably increase it to 30 or so.

**Comment by amazaheri** [comment]
thats interesting, I saw alot of 5 and 10 when coding my mobile services and copied the logic here to determine-basal.js Never saw 11 😊 "Never say never" I will also remove my comment on raw, second thought not sure raw data is reliable to make decisions.

**Comment by scottleibrand** [comment]
Fixed by https://github.com/openaps/openaps-js/commit/01d81d82fbea7ec74872dcb34e4ea537d28db2b2
