### ISSUE TITLE
Bolus snooze wont snooze a low-temp while BG is low and after a mealtime bolus

### ISSUE THREAD

**Issue by esteward** [openaps/openaps-js#26]
Bolus snooze wont snooze a low-temp while BG is low and after a mealtime bolus. I wonder if just having my normal basal rate running post meal time is better than a low-temp (even when my BG is low) as to avoid a rise in BG 90-160 minutes after meal time.

**Comment by scottleibrand** [comment]
@esteward @danamlewis @amazaheri Please see the reference pull request with a proposed solution to this, and LMK what you think.

**Comment by esteward** [comment]
I am still indifferent about whether or not you would want to snooze a low-temp. I guess you have to assume you bolused correctly (in the logic), but if you over bolused and you already have a low BG, then the low-temp makes sense. I am interested to hear @danamlewis and @amazaheri perspectives.

**Comment by amazaheri** [comment]
I need to test this over weekend, as we run it over night for now. I will get back to you soon on this.

**Comment by amazaheri** [comment]
<img width="671" alt="capture" src="https://cloud.githubusercontent.com/assets/8312775/9822218/f7be493e-5873-11e5-9d4d-6720ffd32827.PNG">
Last night results running the loop with above changes.

**Comment by scottleibrand** [comment]
Did you have any bolus IOB at the start of the night?  This won't change
anything for overnight use, just within 2 hours of a bolus.

**Comment by amazaheri** [comment]
We had, we did a correction (.5) before bed.

**Comment by amazaheri** [comment]
I will do a 24/7 Saturday without switching to t:slim and do a comparison as well.

**Comment by scottleibrand** [comment]
Once one of you is satisfied that this works well, please go ahead and merge it.  It has been working well for us.

**Comment by amazaheri** [comment]
another run tonight and I should be good, I tweeted the result from last nigh.

**Comment by amazaheri** [comment]
<img width="960" alt="capture" src="https://cloud.githubusercontent.com/assets/8312775/9839798/7160fed8-5a38-11e5-8165-611f168de70f.PNG

Last night with having Medtronic for whole day.
