### ISSUE TITLE
USB Device location has changed in later Raspberry Pi Kernel

### ISSUE THREAD

**Issue by oskarpearson** [openaps/openaps-js#38]
https://github.com/openaps/openaps-js/blob/3742ae0696a654b3c5a1a530f042b0c5f1b318d5/bin/fix-dead-carelink.sh

The kernel device has changed in recent kernels. It seems to now be /sys/devices/platform/soc/3f980000.usb/buspower

I'll look into this once I'm back from leave.

**Comment by oskarpearson** [comment]
The commit referenced above is untested - I'll try spend some time on it when I've got a Raspberry Pi available.

**Comment by bewest** [comment]
Interesting, should track which version of kernel it changed.
Apparently `bcm2708` module is the broadcom chip that is the RPI itself.

**Comment by scottleibrand** [comment]
Tested and confirmed that /sys/devices/platform/soc/3f980000.usb/buspower properly resets USB on Raspberry Pi 2 with Raspbian Wheezy.  Updated the script (b844c0ce542bf0565399ba6ae3932d34cd2672d0) to check both paths and use whichever exists.

**Comment by scottleibrand** [comment]
Also added a find command to check for other buspower devices in /sys/devices/platform if neither of those exists.  Feel free to reopen this (or just submit a PR) if you think of anything else we should do here.
